### ISSUE TITLE
您好，作者，Filemgr.java类怎么使用的？

### ISSUE THREAD

**Issue by Dreamskya** [physicsboy0709/DfuSeFileManager#2]
![图片](https://user-images.githubusercontent.com/31117684/95041871-80fc0700-070a-11eb-8082-eb2f253d003c.png)
![图片](https://user-images.githubusercontent.com/31117684/95041876-86595180-070a-11eb-87d6-5fc7b7bc8a4f.png)
有尝试给hex和要生成dfu的路径，和不给路径直接运行，但会报错。如上图所示。是哪步操作不对呢？

**Comment by Dreamskya** [comment]
您好，尝试hex转换dfu，code一直为0.文件结束不了。

**Comment by physicsboy0709** [comment]
您好，hex转dfuse没有测试过。请尝试使用multi bin的方式。项目属于前一个工作用到的，目前用不到，所以短时间之内不会更新了。

**Comment by Dreamskya** [comment]
你好，你的意思是bin文件转dfu吗？有相关文章，或者demo参考吗？

**Comment by physicsboy0709** [comment]
对，支持多个bin，并且指定每个bin的起始地址（不进行重叠检验，请自行保证）。
使用方法，编译后--help看一下，如果还没有，看代码吧。release页面不一定最新。

**Comment by Dreamskya** [comment]
好，谢谢作者回复~
